### ISSUE TITLE
prevent abuse using suggestions command

### ISSUE THREAD

**Issue by NanderTGA** [NanderTGA/yabluzo#8]
**EDIT:** This drama is over and any mentions of it have been deleted.

# Problems brought to my attention

- The suggestions should not be able to ping anyone. To fix this I propose to require a space after every `@` character.
  EDIT: pablo suggested to just wrap the `@` sign in backticks. thanks pablo.
- We should ratelimit suggestions per user. I propose 10 per day per ID.
- We should DEFINITELY log who sends suggestions. IDs, session IDs, nicknames, all of it.
- We need a JSON file somewhere which will contain a list of blocked IDs and the reasons of the bans.

This will require however that I finish [msgroom v2](https://github.com/users/NanderTGA/projects/1/views/1) first which will give command handlers information on who triggered the command

Progress on fixing these problems:

- [x] Temporarily disable suggestions
- [ ] Finish msgroom v2
- [ ] Make sure every `@` character is surrounded by backticks
- [ ] Implement banning people
- [ ] Send user information along with suggestion
- [ ] Ratelimit suggestions
- [ ] Enable suggestions again

**Comment by stretch07** [comment]
oh my god you're so fucking pathetic please stop acting so immature
1. You stole all of my concepts, especially the command system. No fucking credits given. Thanks
2. If you don't want me to call you a pedophile, stop denying the evident proof of the immature individual being 6 years old. I have shown you the proof multiple times now and you keep grooming and agreeing with them. It's fucking weird as fuck. Stop it. 'I don't get how I am a pedophile for helping someone' Seriously you don't realize how pedophilic this is??
3. The code I sent you was meant to make you think it was a token logger. Fucking execute it. It doesn't do anything. You're blind as fuck.
4. 'lIbrarY madE by naNdeEr Tga. jOin mY diSocord ChecK oUt the LiBrarY' <= Yeah that's self promoting
  

#problems brought to your attention
* wrap it in backticks, you fucking idiot. Everyone does this.
* you have no idea how easy it is to get another ID
* no, you shouldn't. Make them anonymous
* good idea. I'll do the same with you

watch npm and github take down your library, liar. It's a shame you can't be more reasonable and less pedophile-y
one last thing: your reputation is just as valuable as mine. Watch it.

**Comment by NanderTGA** [comment]
1. As I said you did not invent the commands system, and we both implemented it very differently. I did not steal anything from you. If you think so, tell me what.
2. Send your "proof" of him being 6 years old in here. I still don't believe you.
3. I know it doesn't work, I mentioned it.
4. That's not abuse. Every single bot I've used before on discord has links to their own servers.

- Thanks for the better solution
- I'll just ban it too.
- The suggestions will not be anonymous any longer. I need to know who abuses it and need to know their IDs to ban them.
- You don't even *have* a bot to ban me from. And if you're thinking about banning me from using any bots using your library, that will show to everyone you should NOT be trusted and your unstable library should not be used.
- Please for gods sake catch errors thrown by command handlers. You don't want a bot crashing because of some bad input or something.
- If you really think npm and github will take my stuff down, you should go touch some grass because they won't.
- I have been way too reasonable with your actions in the past, and I am no longer because of your own actions.

**Comment by stretch07** [comment]
> ID acquired: `9687EAS3196HGJ87C2M2ZASCIAGGJZZ1`

friendly reminder IDs are tied to IPs, you are effectively doxing me right now

**Comment by NanderTGA** [comment]
They are generated from more than just your IP.

**Comment by stretch07** [comment]
more than doxing. cool

**Comment by Upwader** [comment]
upvote this post if you like eating dorites

**Comment by stretch07** [comment]
yeah

**Comment by kelbazz** [comment]
god damn i don't really understand the pb here

**Comment by kelbazz** [comment]
is it just for the similarity of the libs ?

**Comment by NanderTGA** [comment]
> is it just for the similarity of the libs ?

That is my point, there is no similarity.
to define a command in msgroom, you define a property on an object
to define one in msgroom-bot, you pass a handler to some function

pablo, what is the problem here? how do we fix it?

**Comment by NanderTGA** [comment]
If we don't sort this out, I will have to block you and lock this thread.
This is not a place I want stupid drama.

**Comment by stretch07** [comment]
the problem is fixed
stop talking to me thanks

**Comment by Hedy88** [comment]
lmfao

**Comment by NanderTGA** [comment]
how'd you get here suddenly?

**Comment by NanderTGA** [comment]
It's been a long time since I last heard from you

**Comment by Hedy88** [comment]
i am here from pure magic.

**Comment by NanderTGA** [comment]
uhhh sure.
I never thought this project would even get this much attention

**Comment by stretch07** [comment]
hey nander, can you delete this issue now? thanks

**Comment by NanderTGA** [comment]
Wait you _actually_ reported me? I am speechless lol.

Unfortunately there is no going back now and I'm not deleting anything either.
How else am I going to keep track of the progress on the suggestions command?

Once you put something on the internet, it's there forever.
It might also be worth mentioning that github themselves is not the place to report drama like this, you can only report it to the maintainers, which is only me in this case.

**Comment by nolanwhy** [comment]
i like pasta

**Comment by NanderTGA** [comment]
> i like pasta

Same

**Comment by NanderTGA** [comment]
After some thinking, I have decided to remove the suggestions command completely, and advise my peers to do the same.
Because of these commands, it was possible to make suggestions very quickly, easily and anonymously, without thinking for even a minute about it.
These circumstances cause people to do dumb things before they realize it's a bad idea.

If you want people to be able to make suggestions or bug reports, refer them to your Discord server or an issue tracker.
On discord they won't do much and creating an issue costs more effort.

**Comment by stretch07** [comment]
i wish there was a way of privately authenticating with other msgroom users

**Comment by NanderTGA** [comment]
other users of the library or as in DMing people on msgroom?

**Comment by stretch07** [comment]
other users
